name: Déploiement automatique de Progitek

on:
  schedule:
    - cron: '0 3 * * *' # Tous les jours à 03:00 UTC
  workflow_dispatch: # Lancement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v3

      - name: Connexion SSH et exécution du script de déploiement
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/progitek
            chmod +x deploy.sh
            ./deploy.sh
