services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # ?? Port 3001 sur ta machine
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: file:./prisma/dev.db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./backend/prisma/dev.db:/var/lib/sqlite/dev.db
    environment:
      SQLITE_DATABASE: dev.db
