version: '3.8'

services:
  backend:
    container_name: progitek-backend-1
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    container_name: progitek-frontend-1
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    container_name: progitek-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: progitek
    volumes:
      - progitek_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  progitek_pgdata:
