version: '3.8'

services:
  db:
    image: postgres:15
    container_name: progitek-db
    restart: always
    environment:
      POSTGRES_USER: theo_postgres
      POSTGRES_PASSWORD: Kwt010100++@
      POSTGRES_DB: progitek_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: progitek-backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://theo_postgres:Kwt010100++@@db:5432/progitek_db
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  pgdata:
